version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "5000:5000"
    volumes:
      - ./quote_gen:/app
    environment:
      - FLASK_ENV=development
  web2:
    build: ./quote_disp
    container_name: disp
    ports:
      - "5001:5001"
    depends_on:
      - web1
    volumes:
      - ./quote_disp:/app
    environment:
      - FLASK_ENV=development
