version: "3.7"
services:
  web1:
    build: ./quote_gen
    ports:
      - "5000" # Only container port specified
    volumes:
      - ./quote_gen:/app
    environment:
      - FLASK_DEBUG=1

  web2:
    build: ./quote_disp
    ports:
      - "5001" # Only container port specified
    depends_on:
      - web1
    volumes:
      - ./quote_disp:/app
    environment:
      - FLASK_DEBUG=1
